name: pxt-buildpr

on: [pull_request]

jobs:
  build:
    name: buildpr

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          npm install
      - name: npm test
        run: |
          npm test
        env:
          PXT_ENV: production
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true